# Generated by Django 3.2.7 on 2021-09-17 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_chioce_text_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 14, 53, 40, 502669, tzinfo=utc)),
        ),
    ]
